spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db2022?characterEncoding=utf-8
      username: root
      password: abc123
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  type-aliases-package: com.study.api.entity
  mapper-locations: classpath:mappers/*Mapper.xml
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
